# This is a basic workflow to help you get started with Actions
name: Create PDF Documents

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Environment variables
env:
  OUPUT_DIRECTORY: output

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: docker.io/asciidoctor/docker-asciidoctor

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Convert AsciiDoc to PDF
        run: |
          asciidoctor-pdf -a pdf-theme=light -a pdf-themesdir=resources/themes sample.adoc -o ${{ env.OUPUT_DIRECTORY }}/sample-light.pdf
          asciidoctor-pdf -a pdf-theme=sepia -a pdf-themesdir=resources/themes sample.adoc -o ${{ env.OUPUT_DIRECTORY }}/sample-sepia.pdf
          asciidoctor-pdf -a pdf-theme=dark -a pdf-themesdir=resources/themes sample.adoc -o ${{ env.OUPUT_DIRECTORY }}/sample-dark.pdf

      # Upload
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Book # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.OUPUT_DIRECTORY }}
